### ISSUE TITLE
Front: Sign In component

### ISSUE THREAD

**Issue by thomasdayan168** [Adi-Hershko/ArtGallery#7]
## Description
We need to create a sign-in component for the frontend of our application. This component should allow users to log in to their account by providing their email address and password. Upon successful authentication, users should be redirected to the dashboard.

## Tasks
- [ ] Design the UI for the sign-in form.
- [ ] Implement the frontend logic for form validation triggered by submit button: When clicking submit, send to the backend the username and the password. If the user is logged in then redirect him to /feeds page. If the auth failed, then pop up a message saying Invalid details.
- [ ] Connect the sign-in form to the backend API for authentication.
